import csv
import random

#The name of your name list
modname = "Poop"

#Set to 1 to have a first and a last name
firstlast = 0

#Set to 1 to have different names for royalty
regnal = 0

#Army Suffixes
army = "Army"
xeno = "Meanies"
gene = "Army"

#Fleet Suffix
fleet = "Navy"

#Alterable
filename = "rok_name.csv"
final = modname + ".txt"

#Not Alterable
with open(filename, newline='') as csvfile:
	vulgar = csv.reader(csvfile, delimiter=',', quotechar='|')
	
	names = []
	next(vulgar)
	for row in vulgar:
		if row[0] not in names:
			names.append(row[0].title())
			
	random.shuffle(names)
	
	f = open(final,"w+")
	f.write(
	"###" + modname + "\n"
	"" + modname + " = {\n"
	
	"\t###SHIPS\n"
	"\n"
	"\tship_names = {\n"
	"\n"
	"\t\tgeneric = {\n"
	"\t\t\t" + " ".join(names[1:51]) + "\n"
	"\t\t}\n"
	"\t\tcorvette = {\n"
	"\t\t\t" + " ".join(names[52:77]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tdestroyer = {\n"
	"\t\t\t" + " ".join(names[78:103]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tcruiser = {\n"
	"\t\t\t" + " ".join(names[104:155]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tbattleship = }\n"
	"\t\t\t" + " ".join(names[156:181]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\ttitan = {\n"
	"\t\t\t" + " ".join(names[182:192]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tcolossus = {\n"
	"\t\t\t" + " ".join(names[193:196]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tscience = {\n"
	"\t\t\t" + " ".join(names[222:248]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tcolonizer = {\n"
	"\t\t\t" + " ".join(names[249:274]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tconstructor = {\n"
	"\t\t\t" + " ".join(names[275:300]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\ttransport = {\n"
	"\t\t\t" + " ".join(names[301:352]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tmilitary_station_small = {\n"
	"\t\t\t" + " ".join(names[353:368]) + "\n"
	"\t\t}\n"
	"\n"
	"\t\tion_cannon = {\n"
	"\t\t\t" + " ".join(names[369:384]) + "\n"
	"\t\t}\n"
	"\n"
	"\t}\n"
	"\n"
	
	"\tfleet_names = {\n"
	"\t\trandom_names = {\n"
	"\t\t\t\"" + "".join(names[385]) +  " " + fleet + "\" " + "\"" + "".join(names[1097]) +  " " + fleet + "\" " + "\"" + "".join(names[1098]) +  " " + fleet + "\" " + "\"" + "".join(names[1099]) +  " " + fleet + "\" " + "\"" + "".join(names[1100]) +  " " + fleet + "\" " + "\"" + "".join(names[1101]) +  " " + fleet + "\" " + "\"" + "".join(names[1102]) +  " " + fleet + "\" " + "\"" + "".join(names[1103]) +  " " + fleet + "\" " + "\"" + "".join(names[1104]) +  " " + fleet + "\" " + "\"" + "".join(names[1105]) +  " " + fleet + "\" " + "\"" + "".join(names[1106]) +  " " + fleet + "\" " + "\"" + "".join(names[1107]) +  " " + fleet + "\" " + "\"" + "".join(names[1108]) +  " " + fleet + "\" " + "\"" + "".join(names[1109]) +  " " + fleet + "\" " + "\"" + "".join(names[1110]) +  " " + fleet + "\" " + "\"" + "".join(names[1111]) +  " " + fleet + "\"\n"
	"\t\t}\n"
	"\n"
	"\n"
	
	"\t###ARMIES\n"
	"\tarmy_names = {\n"
	"\n"
	"\t\tdefense_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[386]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\tassault_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[387]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\tslave_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[388]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\tclone_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[389]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\trobotic_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[390]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\trandroid_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[391]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\tpsionic_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[392]) + " " + army + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\txenomorph_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[393]) + " " + xeno + "\"\n"
	"\t\t}\n"
	"\n"
	"\t\tgene_warrior_army = {\n"
	"\t\t\tsequential name = \"%O% " + "".join(names[394]) + " " + gene + "\"\n"
	"\t\t}\n"
	"\t}\n"
	"\n"
	
	"\t### PLANETS\n"
	"\n"
	"\tplanet_names = {\n"
	"\n"
	"\t\tgeneric = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t\t" + " ".join(names[395:595]) + "\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_desert = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_tropical = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_arid = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_continental = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_ocean = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_tundra = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_alpine = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t\tpc_arctic = {\n"
	"\t\t\tnames = {\n"
	"\t\t\t}\n"
	"\t\t\n"
	"\n"
	"\t}\n"
	"\n"
	"\t### CHARACTERS\n"
	"\n"
	)
	f.close
	
	f = open(final,"a")
	f.write(
	"\tcharacter_names={\n"
	"\t\tdefault = {\n"
	"\t\t\tfull_names ={\n"
	"\t\t\t" + " ".join(names[596:1096]) + "\n"
	"\t\t\t}\n"
	"\n"
	"\t\t\t#Always combined with a second name\n"
	"\t\tdefault = {"
	"\t\t\tfirst_names_male ={\n"
	"\t\t\t}\n"
	"\n"
	"\t\tdefault = {"
	"\t\t\tfirst_names_female ={\n"
	"\t\t\t}\n"
	"\t\t\t# Always combined with a first name\n"
	"\t\tdefault = {"
	"\t\t\tsecond_names ={\n"
	"\t\t\t}\n"
	"\n"
	"\t\tdefault = {"
	"\t\t\tregnal_first_names_male ={\n"
	"\t\t\t}\n"
	"\n"
	"\t\tdefault = {"
	"\t\t\tregnal_first_names_female ={\n"
	"\t\t\t}\n"
	"\n"
	"\t\tdefault = {"
	"\t\t\tregnal_second_names ={\n"
	"\t\t\t}\n"
	"\t\t}\n"
	"\t}\n"
	"}"
	)